### ISSUE TITLE
hey 你好

### ISSUE THREAD

**Issue by ecmadao** [chenjinxinlove/citySelect#1]
hey 你好，
 
抱歉打扰，这里是北京的天气和环境大数据初创公司，[心知天气 thinkpage.cn](http://www.thinkpage.cn/) 。我们是一个技术驱动型的九人小团队，成员来自 Microsoft、Google、JD、Frog Design 这些公司。最近，我们在寻找优秀的[全栈工程师](https://www.lagou.com/jobs/2492101.html)。**我在拉勾上看到了你的简历，觉得你非常合适。**
 
如果你加入，将会成为[心知 SaaS BI 产品](http://www.thinkpage.cn/insights)的创造者中的一员。这个产品是心知目前的绝对重心，致力于为各个受天气影响剧烈的行业搭建数据和可视化平台，同时辅助商业决策。
 
关于这个职位，拉勾上有简略的描述，可以供你参考：

- [node.js 职位](https://www.lagou.com/jobs/2481756.html)
- [全栈 职位](https://www.lagou.com/jobs/2492101.html)
- [后端/架构师 职位](https://www.lagou.com/jobs/2529588.html)

真心希望有机会和你详谈，如果感兴趣的话，可以回复你的电话，或者通过邮件来联系我：wlec@outlook.com ， 我们会和你敲定面试的时间。

打扰了， 期待回复！

**Comment by chenjinxinlove** [comment]
很高兴，能收到您的邀请。其实那份工作还是蛮适合我的。但是我才跟老大谈完，决定暂时不换工作了。谢谢！有机会在合作。

**Comment by ecmadao** [comment]
@chenjinxinlove 
好嘞没关系，谢谢回复，祝好~
